sudo: false
language: python
install:
  - pip install tox-travis
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS quma_test_db;'
  - psql -c 'CREATE DATABASE quma_test_db;' -U postgres
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
script: tox
